name: taks_3mc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3

  intl_phone_field: ^3.2.0
  pinput: ^2.2.31

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^10.4.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  get_it: ^7.6.0
  cloud_firestore: ^4.8.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  another_flushbar: ^1.12.30
  mockito: ^5.4.2

  fake_cloud_firestore: ^2.4.1+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
   - lib/core/assets/images/
